### PR TITLE
Convert component to stateless and cleaned up CSS

### PR DESCRIPTION
**Pull request by eric-do**
See below - I previously had 3 different objects for different conditions, and they were all different by only 2 lines - color and background.

I refactored into styled component, passing in props to the styled component for conditional appearance.

### CODE REVIEW

**Comment by Doughertyg** [comment]
most annoying review ever but could you add more comments to this script? I had to do a lot of digging to find where you define clickhandler and how you're using the passed in arguments. Otherwise it looks good! and good that u refactored to stateless

**Comment by eric-do** [comment]
@Doughertyg I updated code with your feedback. The clickHandler name change broke some of my snapshots so I updated tests for that too. I need your approval before I can merge:
image

**Comment by Doughertyg** [comment]
sweet, thanks, yeah that looks good and reads a bit clearer

**Review by Doughertyg — APPROVED** [review]
The additional comments and method name change look good and improves readability. checks out with me.

**Pull request merged**
