### PR TITLE
Jest tests

### PR DESCRIPTION
**Pull request by eric-do**
Wrote some new tests

### CODE REVIEW

**Comment by Doughertyg** [comment]
filtertest.js line 47, it says expect wrapper filter dropdown to have length 1... why? how is that testing the hover feature? Otherwise it all seems to look good

**Comment by eric-do** [comment]
@Doughertyg that test was incomplete - I had been trying to find a way to simulate hover but still haven't found any success.

Regarding length 1 - that was looking for the specific styled component and verifying it's there, but I removed it anyway because snapshots accomplish the same thing.

I've pushed updated code with the test commented out - need approval

**Comment by eric-do** [comment]
Need this one too, @Doughertyg

**Review by Doughertyg — APPROVED** [review]
Looks good. Still planning to test for hover effect? Line 48 doesn't work?

**Comment by eric-do** [comment]
Not yet, no. I've tried a bunch of alternatives but the state never gets updated in the test:
```
    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      46 |     expect(wrapper.find('FilterDropdown')).toHaveLength(1);
      47 |     wrapper.find('FilterButton').simulate('mouseenter');
    > 48 |     expect(wrapper.state('showMenu')).toBe(true);
         |                                       ^
      49 |   });
      50 | });

      at Object.toBe (__tests__/Filter.test.js:48:39)
```

I've tried different synthetic events, and done with both shallow() and mount(), and no success:
```
wrapper.find('FilterButton').simulate('mouseover');
wrapper.find('FilterButton').simulate('mouseenter');
```
[Docs](https://airbnb.io/enzyme/docs/api/ReactWrapper/simulate.html) don't provide a list of synethetic events.

Not to say I've given up yet but there's just no working solution for me at this time :)

**Pull request merged**
